[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  # Instala dependências na raiz do monorepo
  'NODE_ENV=development npm install'
]

[phases.build]
cmds = [
  # Builda o app e todos os pacotes necessários via turbo
  'cd apps/admin-web && npm run build',
  'cd ../patient-web && npm run build'
]

[start]
# Inicia o app no diretório correto
cmd = 'npm start'