[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
cmds = [
  # Instala dependências na raiz do monorepo
  'NODE_ENV=development npm install'
]

[phases.build]
cmds = [
  # Builda apenas o patient-web app por enquanto
  'cd apps/patient-web && npm run build'
]

[start]
# Inicia o app no diretório correto
cmd = 'cd apps/patient-web && HOSTNAME=0.0.0.0 npm start'

[healthcheck]
# Health check endpoint for container health monitoring
cmd = 'curl -f http://0.0.0.0:3000/api/health || exit 1'