[phases.setup]
nixPkgs = ['nodejs-18_x', 'npm-9_x']

[phases.install]
# Install dependencies from the root of the monorepo
cmds = [
  'NODE_ENV=development npm install'
]

[phases.build]
# Build the specific patient-web app using turbo
cmds = [
  'npm run build'
]

[start]
# Start the patient-web app
cmd = 'npm start' 